### ISSUE TITLE
"please enter existing class"

### ISSUE THREAD

**Issue by ABFoster98** [mucsci-students/2022sp-420-AlarmSquad#31]
When adding incorrect class name, program says "_ was not found, please enter an existing class", but then breaks out of case and is not actually looking for a re-entered class name. Program should either look for class name or the prompt should be different.

**Comment by anOrgandroiD** [comment]
not closing this issue atm, as the easiest solution right now is to break out of the function if the specified class cannot be found. by repeating the prompt, this opens up the window of creating an infinite loop when no classes exist, or forcing the user to rename an existing class regardless of whether they want to. in the future, we might want to prompt the user whether or not they would like to try again, and break if they choose not to. as of now, my fix can be found in the renameClassFix branch

**Comment by mmoyer1** [comment]
Assuming this issue is for the Delete class function. The function should be in a big loop, because if the user wants to delete a class and accidentally misspells the name of a class they want to delete, they wouldn't want to exit, they would want to try again, so we should prompt the user saying that the class name doesn't exist and also allow them to enter it again. If they really just want to try to delete a class and then for some reason after misspelling the name and then want to leave, they can type exit.
